import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable}`}>
        <nav
          style={{
            width: "100%",
            background: "teal",
            padding: "10px",
            color: "white",
            display: "flex",
            gap: "100px",
            justifyContent: "center",
            alignItems: "center",
            fontSize: "30px",
          }}
        >
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
          <Link href="/articles">Articles</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
